---
galaxy_info:
  author: Bert Van Vreckem
  description: A role for managing a Dnsmasq server on CentOS/RHEL 7 or Fedora 16-21.
  company: University College Ghent
  license: Simplified BSD License
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
  categories:
    - networking
dependencies: []
version: 1.1.0
